### ISSUE TITLE
Basic Login/Auth method

### ISSUE THREAD

**Issue by RicardoVelaC** [nbr23/youtube-dl-server#20]
Is possible to add an option to make the URL private? Like a basic HTTP Auth via browser or login page?

I want to publish my site on Internet for my private use when I'm out of my network. But I don't want to be public for everyone. Is now possible without auth?

PD: Actually I'm using a Synology NAS with docker. I have others containers published and accesible on internet but all of them have an auth method.

Thanks!

**Comment by nbr23** [comment]
Hi @RicardoVelaC,

As the goal is to keep this piece of software simple, there is no immediate plan to add this to youtube-dl-server.
It is definitely recommanded however to use nginx or another reverse proxy / web server to serve your content, and any of these will be able to perform the basic authentication.

I am not sure how well it would help with your Synology setup (you would likely need nginx run in its own container rather than on the NAS itself), but I have an ansible role setting this up and allowing basic auth with nginx here: https://github.com/nbr23/ansible-role-youtubedl-server

Cheers!
