### ISSUE TITLE
Large Log Sizes cause UI Lockup - Log Rotate or clear old items?

### ISSUE THREAD

**Issue by nickv2002** [nbr23/youtube-dl-server#25]
I ran regular updates with the server for a few months and eventually got the log size up to 1.2M

```
-rw-r--r--  1 nick nick 1.2M Jan  2 20:55 .ydl-metadata.db
```

This seemed to cause the UI to lock-up/fail to load; simple fix was to delete the log file and everything started working again as expected. Perhaps some way to rotate or clear old items from the log would be a good feature?

Figured I'd post here as a FYI in case anyone has similar issues and as a potential feature request. Thanks for all your work on the project!

**Comment by nbr23** [comment]
Hi @nickv2002 ,

Thanks for the issue, that's an interesting one. An immediate action that can be taken that should help is to go to the Logs tab and his "Purge Logs". I have just added an sqlite vacuuming after the purge log (https://github.com/nbr23/youtube-dl-server/commit/4e431005ae59277c9355154285a6f4faa228776a), so that sqlite shrinks the db after cleaning up the log entries.
I will definitely look into rotating or having an option to automatically clean up logs after a certain size / date so users don't have to manually purge.

**Comment by nickv2002** [comment]
I tried the "Purge Logs" but the UI was so slow that it didn't work. Underlying issue is probably with the API actually because I tried the "Purge Logs" via the API call too but that didn't work either.  It's no big deal to delete the file and start over so not a major issue, just an areas to consider for future improvements. Thanks!

**Comment by nbr23** [comment]
Ah alright, I see. I will do more testing on my end and work on this. Thanks again!

**Comment by nbr23** [comment]
Log rotating added in https://github.com/nbr23/youtube-dl-server/commit/172cf7b3778ecf2c9f2de72a70abcd9893e6658a
By default we will keep 100 entries. This can be edited in `config.yml`:
```
ydl_server:
[…]
  max_log_entries: 10 # Maximum number of job log history to keep
[…]
```
