### ISSUE TITLE
Handling multiple filenames

### ISSUE THREAD

**Issue by blackerking** [nbr23/youtube-dl-server#37]
Sometimes I am loading files with a master.m3u8 suddenly all files are named master but replaced by the last one.
It would be neat if the files getting a number after their name and not replaced.

**Comment by nbr23** [comment]
Hi @blackerking,
Do you know if youtube-dl has a way of handling this?
Do you have a master.m3u8 link you can share for testing?

Thanks,

**Comment by blackerking** [comment]
It seems youttube-dl has a -o for a named filename flag:
`youtube-dl -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]' -o video.mp4 https://www.youtube.com/watch?v=5yx6BWlEVcY`
Here is the files with the same name where I've discovered the "error":
- https://rbbmediaadp-vh.akamaihd.net/i/content/5f/63/5f631177-1902-44fb-8933-d42554078829/5f631177-1902-44fb-8933-d42554078829_,512k,128k,256k,1024k,1800k,.mp4.csmil/master.m3u8
- https://rbbmediaadp-vh.akamaihd.net/i/content/7a/bd/7abd9bdf-9d13-4dc9-bbf8-de5526b48e82/7abd9bdf-9d13-4dc9-bbf8-de5526b48e82_,512k,128k,256k,1024k,1800k,.mp4.csmil/master.m3u8

**Comment by nbr23** [comment]
Hi @blackerking 
Yeah unfortunately, without using the -o (which youtube-dl-server doesn't really allow at this point) it seems it will be tricky.
I tried to play with some of the [youtube-dl output templates](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#output-template) but even with the `autonumber` it does not seem to download both videos if we pass the two links. The only thing I found that work would be to use `(url)s` in your output template, so the video is named after its url. As they are unique, it will create unique filenames instead of just master.mp4. It is not a pretty result however.

This is mostly a youtube-dl limitation. I will see if there is a not too complicated safe way to allow users to specify filenames through the UI, but for now I am afraid we are left with playing with the output template.

**Comment by nbr23** [comment]
@jim60105 unfortunately the timestamp variable seems to be the timestamp of the video release, not timestamp of the execution of the download:
> timestamp (numeric): UNIX timestamp of the moment the video became available

In addition, it seems it is not always set (in my couple of tests it was `NA`).

**Comment by nbr23** [comment]
`epoch` though seems to do the trick!
> epoch (numeric): Unix epoch when creating the file
