### ISSUE TITLE
Soundcloud extraction doesn't work

### ISSUE THREAD

**Issue by blackerking** [nbr23/youtube-dl-server#5]
When using youtube-dl as standalone program it can download files from soundcloud.com.
Otherwise you're using the docker container it cannot:
ERROR: requested format not available

**Comment by nbr23** [comment]
Hi @blackerking,
Thanks for the issue, this should be fixed with https://github.com/nbr23/youtube-dl-server/commit/e5a6c664c5af5be4d470c01c5ba2ab0daace9f68
Let me know if that doesn't work out. I basically updated the format being requested to be broader to prevent it from not finding what it wants.

Cheers,
Max

**Comment by blackerking** [comment]
Worked like a charm. Thank you.
