### ISSUE TITLE
Docker build with ffmpeg git master build to fix yt-dlp sponsorblock

### ISSUE THREAD

**Issue by notDavid** [nbr23/youtube-dl-server#67]
Hi there, currently there's a [bug in ffmpeg, which is used by yt-dlp](https://github.com/yt-dlp/yt-dlp/issues/871#issuecomment-1102417981), which causes Sponsorblock to fail.

Since it's going to take a while before the next major ffmpeg version is released, i was wondering if you would consider/it would be possible to make a Docker build/tag containing the ffmpeg master build?

What i manually ran in the container to make it work is:

```sh
apk del ffmpeg
wget 'https://raw.githubusercontent.com/Tzahi12345/YoutubeDL-Material/8dac9d1806f4ff32cb620f4a94fc7dd60fb3acf7/ffmpeg-fetch.sh'
# remove apt-get
sed -i '/apt-get/d' ffmpeg-fetch.sh
apk update
apk add curl
apk add xz
chmod u+x ffmpeg-fetch.sh
./ffmpeg-fetch.sh
```

...which fetches and installs the ffmpeg master builds from https://johnvansickle.com/ffmpeg/

Thank you :-)

**Comment by nbr23** [comment]
Thanks for the note @notDavid, do you have a test case for this so I can validate?

**Comment by nbr23** [comment]
Thanks again, latest images should be good to go! https://github.com/nbr23/youtube-dl-server/commit/04ff74192287e4504b8c1c0bd2003f5a0d4486d2

**Comment by nbr23** [comment]
I think it's fine to leave as is. I'll try to keep an eye on the ffmpeg fix's inclusion in stable. I think adding one more tag will be more confusing than anything, especially since it won't be needed once that fix is officially in.
If we end up having actual issues with ffmpeg, I'll do that, but in the meantime I'll keep to lowest effort ;)

Thanks again!
