### ISSUE TITLE
Feature: update the yt_dlp (or youtube-dl) module

### ISSUE THREAD

**Issue by oleg-fiksel** [nbr23/youtube-dl-server#71]
It would be nice to have the feature to update the `yt_dlp` module without rebuilding the Docker container.
Something like this: https://github.com/ToWatchList/twl-dl-server/blob/main/ydl_server/ydlhandler.py#L80
Also, maybe, with an API endpoint: https://github.com/ToWatchList/twl-dl-server/blob/main/youtube-dl-server.py#L108

**Comment by nbr23** [comment]
Hi @oleg-fiksel,
I had this feature (as you can see in this fork https://github.com/ToWatchList/twl-dl-server/blob/main/youtube-dl-server.py#L108) but it proved to introduce issues when dependencies needed to be upgraded, to require a larger docker image for wheels building dependencies, etc.
It is usually preferred to upgrade docker deployed applications by pulling the latest image rather than modifying the running container's binaries, so I reverted back to this.

Thanks!
