### ISSUE TITLE
Help outputting/saving files to a directory outside of docker container 

### ISSUE THREAD

**Issue by Aughen** [nbr23/youtube-dl-server#99]
Hello, I am using DLP with docker on windows 10 and trying to save the files automatically to my P: drive. I have tried to edit the config file and add it to the command to create the docker container, but it never saves it to the dive. 

I tried putting it here in the config:
output: '/youtube-dl/%(title)s [%(id)s].%(ext)s' # output directory template

Like 'P:/YouTube/youtube-dl/%(title)s [%(id)s].%(ext)s'

tried " instead of ' 

tried adding this in various places
-o "P:/YouTube/youtube-dl/%(title)s.%(ext)s"

But that doesn't work. I know it is something stupid I am missing, but i am just learning docker containers. 

any help would be appreciated. 

Thank you 
Jusitn

**Comment by nbr23** [comment]
Hi @Aughen ,

I don't know much about windows, but you likely want to use mounts/volumes https://docs.docker.com/storage/volumes/ to "map" your windows directory into your docker container.

So you'll mount "P:/YouTube" to "/youtube-dl/", and then should be good to go since this is the directory inside docker that the application is saving to by default (https://github.com/nbr23/youtube-dl-server/blob/master/config.yml#L5-L6)

Hope that helps!
